package trading

type Instrument struct {
	ID     int
	Symbol string
}

var Instruments = []Instrument{
	// ---- original 20 (101-120) ----
	{ID: 101, Symbol: "BTC_USDT"},
	{ID: 102, Symbol: "ETH_USDT"},
	{ID: 103, Symbol: "BNB_USDT"},
	{ID: 104, Symbol: "XRP_USDT"},
	{ID: 105, Symbol: "SOL_USDT"},
	{ID: 106, Symbol: "ADA_USDT"},
	{ID: 107, Symbol: "DOGE_USDT"},
	{ID: 108, Symbol: "MATIC_USDT"},
	{ID: 109, Symbol: "LTC_USDT"},
	{ID: 110, Symbol: "DOT_USDT"},
	{ID: 111, Symbol: "AVAX_USDT"},
	{ID: 112, Symbol: "LINK_USDT"},
	{ID: 113, Symbol: "UNI_USDT"},
	{ID: 114, Symbol: "ATOM_USDT"},
	{ID: 115, Symbol: "TRX_USDT"},
	{ID: 116, Symbol: "ETC_USDT"},
	{ID: 117, Symbol: "FIL_USDT"},
	{ID: 118, Symbol: "ICP_USDT"},
	{ID: 119, Symbol: "APT_USDT"},
	{ID: 120, Symbol: "ARB_USDT"},
	// ---- batch 2 (121-200) ----
	{ID: 121, Symbol: "OP_USDT"},
	{ID: 122, Symbol: "INJ_USDT"},
	{ID: 123, Symbol: "SUI_USDT"},
	{ID: 124, Symbol: "STX_USDT"},
	{ID: 125, Symbol: "IMX_USDT"},
	{ID: 126, Symbol: "GRT_USDT"},
	{ID: 127, Symbol: "AAVE_USDT"},
	{ID: 128, Symbol: "SNX_USDT"},
	{ID: 129, Symbol: "MKR_USDT"},
	{ID: 130, Symbol: "COMP_USDT"},
	{ID: 131, Symbol: "LDO_USDT"},
	{ID: 132, Symbol: "RPL_USDT"},
	{ID: 133, Symbol: "FTM_USDT"},
	{ID: 134, Symbol: "NEAR_USDT"},
	{ID: 135, Symbol: "ALGO_USDT"},
	{ID: 136, Symbol: "VET_USDT"},
	{ID: 137, Symbol: "HBAR_USDT"},
	{ID: 138, Symbol: "EGLD_USDT"},
	{ID: 139, Symbol: "XTZ_USDT"},
	{ID: 140, Symbol: "THETA_USDT"},
	{ID: 141, Symbol: "AXS_USDT"},
	{ID: 142, Symbol: "SAND_USDT"},
	{ID: 143, Symbol: "MANA_USDT"},
	{ID: 144, Symbol: "ENJ_USDT"},
	{ID: 145, Symbol: "CHZ_USDT"},
	{ID: 146, Symbol: "ONE_USDT"},
	{ID: 147, Symbol: "ZIL_USDT"},
	{ID: 148, Symbol: "BAT_USDT"},
	{ID: 149, Symbol: "ZRX_USDT"},
	{ID: 150, Symbol: "CRV_USDT"},
	{ID: 151, Symbol: "1INCH_USDT"},
	{ID: 152, Symbol: "DYDX_USDT"},
	{ID: 153, Symbol: "SUSHI_USDT"},
	{ID: 154, Symbol: "YFI_USDT"},
	{ID: 155, Symbol: "BAL_USDT"},
	{ID: 156, Symbol: "REN_USDT"},
	{ID: 157, Symbol: "KNC_USDT"},
	{ID: 158, Symbol: "OCEAN_USDT"},
	{ID: 159, Symbol: "ROSE_USDT"},
	{ID: 160, Symbol: "CELO_USDT"},
	{ID: 161, Symbol: "CFX_USDT"},
	{ID: 162, Symbol: "KAVA_USDT"},
	{ID: 163, Symbol: "BAND_USDT"},
	{ID: 164, Symbol: "SKL_USDT"},
	{ID: 165, Symbol: "ZEN_USDT"},
	{ID: 166, Symbol: "DASH_USDT"},
	{ID: 167, Symbol: "XMR_USDT"},
	{ID: 168, Symbol: "ZEC_USDT"},
	{ID: 169, Symbol: "QTUM_USDT"},
	{ID: 170, Symbol: "ONT_USDT"},
	{ID: 171, Symbol: "ICX_USDT"},
	{ID: 172, Symbol: "WLD_USDT"},
	{ID: 173, Symbol: "TIA_USDT"},
	{ID: 174, Symbol: "SEI_USDT"},
	{ID: 175, Symbol: "JTO_USDT"},
	{ID: 176, Symbol: "PYTH_USDT"},
	{ID: 177, Symbol: "JUP_USDT"},
	{ID: 178, Symbol: "STRK_USDT"},
	{ID: 179, Symbol: "MANTA_USDT"},
	{ID: 180, Symbol: "DYM_USDT"},
	{ID: 181, Symbol: "ETHFI_USDT"},
	{ID: 182, Symbol: "ENA_USDT"},
	{ID: 183, Symbol: "W_USDT"},
	{ID: 184, Symbol: "IO_USDT"},
	{ID: 185, Symbol: "ZK_USDT"},
	{ID: 186, Symbol: "LISTA_USDT"},
	{ID: 187, Symbol: "RENDER_USDT"},
	{ID: 188, Symbol: "FET_USDT"},
	{ID: 189, Symbol: "AGIX_USDT"},
	{ID: 190, Symbol: "OCEAN_USDT"},
	{ID: 191, Symbol: "NMR_USDT"},
	{ID: 192, Symbol: "RAD_USDT"},
	{ID: 193, Symbol: "MAGIC_USDT"},
	{ID: 194, Symbol: "GMX_USDT"},
	{ID: 195, Symbol: "PENDLE_USDT"},
	{ID: 196, Symbol: "WIF_USDT"},
	{ID: 197, Symbol: "BONK_USDT"},
	{ID: 198, Symbol: "BOME_USDT"},
	{ID: 199, Symbol: "POPCAT_USDT"},
	{ID: 200, Symbol: "MEW_USDT"},
	// ---- batch 3 (201-300) ----
	{ID: 201, Symbol: "NOT_USDT"},
	{ID: 202, Symbol: "DOGS_USDT"},
	{ID: 203, Symbol: "HMSTR_USDT"},
	{ID: 204, Symbol: "CATI_USDT"},
	{ID: 205, Symbol: "EIGEN_USDT"},
	{ID: 206, Symbol: "SCR_USDT"},
	{ID: 207, Symbol: "NEIRO_USDT"},
	{ID: 208, Symbol: "1000SATS_USDT"},
	{ID: 209, Symbol: "ORDI_USDT"},
	{ID: 210, Symbol: "LUNC_USDT"},
	{ID: 211, Symbol: "USTC_USDT"},
	{ID: 212, Symbol: "BLUR_USDT"},
	{ID: 213, Symbol: "NFP_USDT"},
	{ID: 214, Symbol: "AI_USDT"},
	{ID: 215, Symbol: "XAI_USDT"},
	{ID: 216, Symbol: "MEME_USDT"},
	{ID: 217, Symbol: "PANDORA_USDT"},
	{ID: 218, Symbol: "ACE_USDT"},
	{ID: 219, Symbol: "BEAMX_USDT"},
	{ID: 220, Symbol: "PYUSD_USDT"},
	{ID: 221, Symbol: "ARKM_USDT"},
	{ID: 222, Symbol: "CYBER_USDT"},
	{ID: 223, Symbol: "HOOK_USDT"},
	{ID: 224, Symbol: "MINA_USDT"},
	{ID: 225, Symbol: "SFP_USDT"},
	{ID: 226, Symbol: "HIGH_USDT"},
	{ID: 227, Symbol: "FLOW_USDT"},
	{ID: 228, Symbol: "LOOM_USDT"},
	{ID: 229, Symbol: "IOST_USDT"},
	{ID: 230, Symbol: "WIN_USDT"},
	{ID: 231, Symbol: "HOT_USDT"},
	{ID: 232, Symbol: "KEY_USDT"},
	{ID: 233, Symbol: "CELR_USDT"},
	{ID: 234, Symbol: "REEF_USDT"},
	{ID: 235, Symbol: "RLC_USDT"},
	{ID: 236, Symbol: "OGN_USDT"},
	{ID: 237, Symbol: "MTL_USDT"},
	{ID: 238, Symbol: "OXT_USDT"},
	{ID: 239, Symbol: "NKN_USDT"},
	{ID: 240, Symbol: "TLM_USDT"},
	{ID: 241, Symbol: "ALICE_USDT"},
	{ID: 242, Symbol: "DENT_USDT"},
	{ID: 243, Symbol: "CTSI_USDT"},
	{ID: 244, Symbol: "MASK_USDT"},
	{ID: 245, Symbol: "SLP_USDT"},
	{ID: 246, Symbol: "ARDR_USDT"},
	{ID: 247, Symbol: "MDT_USDT"},
	{ID: 248, Symbol: "FOR_USDT"},
	{ID: 249, Symbol: "POLS_USDT"},
	{ID: 250, Symbol: "AUCTION_USDT"},
	{ID: 251, Symbol: "FLUX_USDT"},
	{ID: 252, Symbol: "FARM_USDT"},
	{ID: 253, Symbol: "ALPHA_USDT"},
	{ID: 254, Symbol: "BETA_USDT"},
	{ID: 255, Symbol: "DEGO_USDT"},
	{ID: 256, Symbol: "RARE_USDT"},
	{ID: 257, Symbol: "LINA_USDT"},
	{ID: 258, Symbol: "PROS_USDT"},
	{ID: 259, Symbol: "IDEX_USDT"},
	{ID: 260, Symbol: "WAXP_USDT"},
	{ID: 261, Symbol: "CVP_USDT"},
	{ID: 262, Symbol: "HARD_USDT"},
	{ID: 263, Symbol: "BURGER_USDT"},
	{ID: 264, Symbol: "BEL_USDT"},
	{ID: 265, Symbol: "WING_USDT"},
	{ID: 266, Symbol: "COTI_USDT"},
	{ID: 267, Symbol: "TROY_USDT"},
	{ID: 268, Symbol: "VITE_USDT"},
	{ID: 269, Symbol: "FUN_USDT"},
	{ID: 270, Symbol: "ERN_USDT"},
	{ID: 271, Symbol: "GTC_USDT"},
	{ID: 272, Symbol: "ILV_USDT"},
	{ID: 273, Symbol: "PEOPLE_USDT"},
	{ID: 274, Symbol: "ANT_USDT"},
	{ID: 275, Symbol: "FORTH_USDT"},
	{ID: 276, Symbol: "BAKE_USDT"},
	{ID: 277, Symbol: "XVS_USDT"},
	{ID: 278, Symbol: "CHESS_USDT"},
	{ID: 279, Symbol: "AUTO_USDT"},
	{ID: 280, Symbol: "TKO_USDT"},
	{ID: 281, Symbol: "PHA_USDT"},
	{ID: 282, Symbol: "DODO_USDT"},
	{ID: 283, Symbol: "SXP_USDT"},
	{ID: 284, Symbol: "UNFI_USDT"},
	{ID: 285, Symbol: "ORN_USDT"},
	{ID: 286, Symbol: "UTK_USDT"},
	{ID: 287, Symbol: "XVG_USDT"},
	{ID: 288, Symbol: "FIRO_USDT"},
	{ID: 289, Symbol: "CLV_USDT"},
	{ID: 290, Symbol: "QI_USDT"},
	{ID: 291, Symbol: "PORTO_USDT"},
	{ID: 292, Symbol: "SANTOS_USDT"},
	{ID: 293, Symbol: "LAZIO_USDT"},
	{ID: 294, Symbol: "CITY_USDT"},
	{ID: 295, Symbol: "PSG_USDT"},
	{ID: 296, Symbol: "ATM_USDT"},
	{ID: 297, Symbol: "OG_USDT"},
	{ID: 298, Symbol: "ASR_USDT"},
	{ID: 299, Symbol: "ACM_USDT"},
	{ID: 300, Symbol: "AFA_USDT"},
}

var SymbolToID map[string]int
var IDToSymbol map[int]string

func init() {
	SymbolToID = make(map[string]int)
	IDToSymbol = make(map[int]string)
	for _, inst := range Instruments {
		SymbolToID[inst.Symbol] = inst.ID
		IDToSymbol[inst.ID] = inst.Symbol
	}
}
