port 26381
bind 127.0.0.1

# monitor pair2 primary — "mymaster2" used in Go code
sentinel monitor mymaster2 127.0.0.1 6383 1

# how long (ms) primary must be unreachable before failover
sentinel down-after-milliseconds mymaster2 5000

# how long (ms) to wait for replica to catch up during failover
sentinel failover-timeout mymaster2 10000

# how many replicas reconfigured at once
sentinel parallel-syncs mymaster2 1

loglevel notice
logfile "redis-sentinel2.log"