port 6382
bind 127.0.0.1

# replicate from pair2 primary
replicaof 127.0.0.1 6383

# replica is read-only by default
replica-read-only yes

# persistence
dbfilename dump-pair2-replica.rdb
dir ./

# logging
loglevel notice
logfile "redis-pair2-replica.log"