port 26381
bind 127.0.0.1

sentinel monitor mymaster2 127.0.0.1 6383 1
sentinel down-after-milliseconds mymaster2 5000
sentinel failover-timeout mymaster2 10000
sentinel parallel-syncs mymaster2 1

loglevel notice
logfile "redis-sentinel2.log"