port 6380
bind 127.0.0.1

# persistence
save 900 1
save 300 10
save 60 10000
dbfilename dump-primary.rdb
dir ./

# replication
replica-lazy-flush no

# logging
loglevel notice
logfile "redis-primary.log"